from app import db
from . import Utils


class User(db.Model):
    """
    User dataclass, has:
    - Name
    - Surname
    - Avatar url
    - userID
    - nick
    """
    __tablename__ = "users"
    _id = db.Column(db.Integer, primary_key=True, name="id")
    uuid = db.Column(db.String(40), nullable=False, default=Utils.str_uuid4)
    nick = db.Column(db.String(30), unique=True, nullable=False)
    name = db.Column(db.String(50), nullable=False)
    surname = db.Column(db.String(50), nullable=False)

    @property
    def avatar_url(self) -> str:
        return f"https://picsum.photos/seed/{self.uuid}/200/200"

    @db.validates("uuid")
    def uuid_edit_blocker(self, key, value):
        """This will prevent you from changing the UUID of this object when editing"""
        if self.uuid:  # Already exists
            raise ValueError("UUID is autogenerated and can not be modified!")
        return value

    def __init__(self, nick: str, name: str, surname: str, **kwargs):
        self.nick = nick
        self.name = name
        self.surname = surname
        super(User, self).__init__(**kwargs)

    def __repr__(self):
        return f"[USER] {self.name} {self.nick} {self.surname}"
